import type { SettingConfig } from '~~/shared/types/settings'

// 存储提供商的枚举值
export const STORAGE_PROVIDERS = ['local', 's3', 'openlist'] as const
export type StorageProvider = (typeof STORAGE_PROVIDERS)[number]

export const DEFAULT_SETTINGS = [
  // NAMESPACE: system
  {
    namespace: 'system',
    key: 'firstLaunch',
    type: 'boolean',
    value: true,
    defaultValue: true,
    label: 'settings.system.firstLaunch.label',
    description: 'settings.system.firstLaunch.description',
    isReadonly: true,
  },
  // NAMESPACE: app
  {
    namespace: 'app',
    key: 'title',
    type: 'string',
    defaultValue: 'ChronoFrame',
    label: 'settings.app.title.label',
    description: 'settings.app.title.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'slogan',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.slogan.label',
    description: 'settings.app.slogan.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'author',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.author.label',
    description: 'settings.app.author.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'avatarUrl',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.avatarUrl.label',
    description: 'settings.app.avatarUrl.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.theme',
    type: 'string',
    defaultValue: 'system',
    enum: ['light', 'dark', 'system'],
    label: 'settings.app.appearance.theme.label',
    description: 'settings.app.appearance.theme.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'upload.maxFileSize',
    type: 'number',
    defaultValue: 256,
    label: 'settings.app.upload.maxFileSize.label',
    description: 'settings.app.upload.maxFileSize.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'upload.duplicateCheck.enabled',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.system.upload.duplicateCheck.enabled.label',
    description: 'settings.system.upload.duplicateCheck.enabled.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'upload.duplicateCheck.mode',
    type: 'string',
    defaultValue: 'skip',
    enum: ['warn', 'block', 'skip'],
    label: 'settings.system.upload.duplicateCheck.mode.label',
    description: 'settings.system.upload.duplicateCheck.mode.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'ml.language',
    type: 'string',
    defaultValue: 'en',
    enum: ['en', 'zh-CN', 'zh-TW', 'ja'] as const,
    label: 'settings.system.ml.language.label',
    description: 'settings.system.ml.language.description',
  },
  {
    namespace: 'system',
    key: 'ml.enabled',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.system.ml.enabled.label',
    description: 'settings.system.ml.enabled.description',
  },
  {
    namespace: 'system',
    key: 'ml.localAiBaseUrl',
    type: 'string',
    defaultValue:
      process.env.ML_LOCALAI_BASE_URL || 'http://chronoframe-localai:8080',
    label: 'settings.system.ml.localAiBaseUrl.label',
    description: 'settings.system.ml.localAiBaseUrl.description',
  },
  {
    namespace: 'system',
    key: 'ml.vlmProvider',
    type: 'string',
    defaultValue: process.env.ML_VLM_PROVIDER || 'openai-compatible',
    enum: ['openai', 'openai-compatible', 'localai'],
    label: 'settings.system.ml.vlmProvider.label',
    description: 'settings.system.ml.vlmProvider.description',
  },
  {
    namespace: 'system',
    key: 'ml.vlmBaseUrl',
    type: 'string',
    defaultValue: process.env.ML_VLM_BASE_URL || '',
    label: 'settings.system.ml.vlmBaseUrl.label',
    description: 'settings.system.ml.vlmBaseUrl.description',
  },
  {
    namespace: 'system',
    key: 'ml.vlmApiKey',
    type: 'string',
    defaultValue: process.env.ML_VLM_API_KEY || '',
    label: 'settings.system.ml.vlmApiKey.label',
    description: 'settings.system.ml.vlmApiKey.description',
    isSecret: true,
  },
  {
    namespace: 'system',
    key: 'ml.vlmModel',
    type: 'string',
    defaultValue: process.env.ML_VLM_MODEL || '',
    label: 'settings.system.ml.vlmModel.label',
    description: 'settings.system.ml.vlmModel.description',
  },
  {
    namespace: 'system',
    key: 'ml.embeddingBaseUrl',
    type: 'string',
    defaultValue: process.env.ML_EMBEDDING_BASE_URL || 'https://api.jina.ai/v1',
    label: 'settings.system.ml.embeddingBaseUrl.label',
    description: 'settings.system.ml.embeddingBaseUrl.description',
  },
  {
    namespace: 'system',
    key: 'ml.embeddingApiKey',
    type: 'string',
    defaultValue: process.env.ML_EMBEDDING_API_KEY || '',
    label: 'settings.system.ml.embeddingApiKey.label',
    description: 'settings.system.ml.embeddingApiKey.description',
    isSecret: true,
  },
  {
    namespace: 'system',
    key: 'ml.embeddingModel',
    type: 'string',
    defaultValue: process.env.ML_EMBEDDING_MODEL || '',
    label: 'settings.system.ml.embeddingModel.label',
    description: 'settings.system.ml.embeddingModel.description',
  },
  {
    namespace: 'system',
    key: 'ml.vectorProvider',
    type: 'string',
    defaultValue: process.env.ML_VECTOR_PROVIDER || 'qdrant',
    enum: ['qdrant'],
    label: 'settings.system.ml.vectorProvider.label',
    description: 'settings.system.ml.vectorProvider.description',
  },
  {
    namespace: 'system',
    key: 'ml.vectorBaseUrl',
    type: 'string',
    defaultValue:
      process.env.ML_VECTOR_BASE_URL || 'http://chronoframe-qdrant:6333',
    label: 'settings.system.ml.vectorBaseUrl.label',
    description: 'settings.system.ml.vectorBaseUrl.description',
  },
  {
    namespace: 'system',
    key: 'ml.vectorApiKey',
    type: 'string',
    defaultValue: process.env.ML_VECTOR_API_KEY || '',
    label: 'settings.system.ml.vectorApiKey.label',
    description: 'settings.system.ml.vectorApiKey.description',
    isSecret: true,
  },
  {
    namespace: 'system',
    key: 'ml.vectorCollectionPrefix',
    type: 'string',
    defaultValue: process.env.ML_VECTOR_COLLECTION_PREFIX || 'chronoframe',
    label: 'settings.system.ml.vectorCollectionPrefix.label',
    description: 'settings.system.ml.vectorCollectionPrefix.description',
  },
  {
    namespace: 'system',
    key: 'ml.faceModel',
    type: 'string',
    defaultValue: process.env.ML_FACE_MODEL || '',
    label: 'settings.system.ml.faceModel.label',
    description: 'settings.system.ml.faceModel.description',
  },
  {
    namespace: 'system',
    key: 'ml.autoTag.enabled',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.system.ml.autoTag.enabled.label',
    description: 'settings.system.ml.autoTag.enabled.description',
  },
  {
    namespace: 'system',
    key: 'ml.autoTag.minScore',
    type: 'number',
    defaultValue: 0.35,
    label: 'settings.system.ml.autoTag.minScore.label',
    description: 'settings.system.ml.autoTag.minScore.description',
  },
  {
    namespace: 'system',
    key: 'ml.aiDescription.enabled',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.system.ml.aiDescription.enabled.label',
    description: 'settings.system.ml.aiDescription.enabled.description',
  },
  {
    namespace: 'system',
    key: 'ml.semanticSearch.enabled',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.system.ml.semanticSearch.enabled.label',
    description: 'settings.system.ml.semanticSearch.enabled.description',
  },
  {
    namespace: 'system',
    key: 'ml.faceAlbum.enabled',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.system.ml.faceAlbum.enabled.label',
    description: 'settings.system.ml.faceAlbum.enabled.description',
  },
  {
    namespace: 'system',
    key: 'ml.faceCluster.threshold',
    type: 'number',
    defaultValue: 0.72,
    label: 'settings.system.ml.faceCluster.threshold.label',
    description: 'settings.system.ml.faceCluster.threshold.description',
  },
  {
    namespace: 'system',
    key: 'ml.ocr.enabled',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.system.ml.ocr.enabled.label',
    description: 'settings.system.ml.ocr.enabled.description',
  },
  {
    namespace: 'system',
    key: 'webglImageViewerDebug',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.system.webglImageViewerDebug.label',
    description: 'settings.system.webglImageViewerDebug.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'auth.github.enabled',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.system.auth.github.enabled.label',
    description: 'settings.system.auth.github.enabled.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'auth.github.clientId',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.auth.github.clientId.label',
    description: 'settings.system.auth.github.clientId.description',
  },
  {
    namespace: 'system',
    key: 'auth.github.clientSecret',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.auth.github.clientSecret.label',
    description: 'settings.system.auth.github.clientSecret.description',
    isSecret: true,
  },
  {
    namespace: 'system',
    key: 'auth.oidc.enabled',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.system.auth.oidc.enabled.label',
    description: 'settings.system.auth.oidc.enabled.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'auth.oidc.label',
    type: 'string',
    defaultValue: 'OIDC',
    label: 'settings.system.auth.oidc.label.label',
    description: 'settings.system.auth.oidc.label.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'auth.oidc.issuer',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.auth.oidc.issuer.label',
    description: 'settings.system.auth.oidc.issuer.description',
  },
  {
    namespace: 'system',
    key: 'auth.oidc.clientId',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.auth.oidc.clientId.label',
    description: 'settings.system.auth.oidc.clientId.description',
  },
  {
    namespace: 'system',
    key: 'auth.oidc.clientSecret',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.auth.oidc.clientSecret.label',
    description: 'settings.system.auth.oidc.clientSecret.description',
    isSecret: true,
  },
  {
    namespace: 'system',
    key: 'auth.oidc.scope',
    type: 'string',
    defaultValue: 'openid email profile',
    label: 'settings.system.auth.oidc.scope.label',
    description: 'settings.system.auth.oidc.scope.description',
  },
  {
    namespace: 'system',
    key: 'auth.oidc.clientAuthMethod',
    type: 'string',
    defaultValue: 'client_secret_post',
    enum: ['client_secret_post', 'client_secret_basic'],
    label: 'settings.system.auth.oidc.clientAuthMethod.label',
    description: 'settings.system.auth.oidc.clientAuthMethod.description',
  },
  // NAMESPACE: privacy
  {
    namespace: 'privacy',
    key: 'upload.autoEraseLocation',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.privacy.upload.autoEraseLocation.label',
    description: 'settings.privacy.upload.autoEraseLocation.description',
    isPublic: true,
  },
  // NAMESPACE: map
  {
    namespace: 'map',
    key: 'provider',
    type: 'string',
    defaultValue: 'maplibre',
    enum: ['mapbox', 'maplibre'],
    label: 'settings.map.provider.label',
    description: 'settings.map.provider.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'mapbox.token',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.mapbox.token.label',
    description: 'settings.map.mapbox.token.description',
  },
  {
    namespace: 'map',
    key: 'mapbox.style',
    type: 'string',
    defaultValue: 'mapbox://styles/mapbox/standard',
    label: 'settings.map.mapbox.style.label',
    description: 'settings.map.mapbox.style.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'maplibre.token',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.maplibre.token.label',
    description: 'settings.map.maplibre.token.description',
  },
  {
    namespace: 'map',
    key: 'maplibre.style',
    type: 'string',
    defaultValue: '/maps/style.json?v=global',
    label: 'settings.map.maplibre.style.label',
    description: 'settings.map.maplibre.style.description',
    isPublic: true,
  },
  // NAMESPACE: location
  {
    namespace: 'location',
    key: 'language',
    type: 'string',
    defaultValue: 'en',
    enum: ['en', 'zh-CN', 'zh-TW', 'ja'] as const,
    label: 'settings.location.language.label',
    description: 'settings.location.language.description',
    isPublic: true,
  },
  {
    namespace: 'location',
    key: 'mapbox.token',
    type: 'string',
    defaultValue: '',
    label: 'settings.location.mapbox.token.label',
    description: 'settings.location.mapbox.token.description',
  },
  {
    namespace: 'location',
    key: 'nominatim.baseUrl',
    type: 'string',
    defaultValue: '',
    label: 'settings.location.nominatim.baseUrl.label',
    description: 'settings.location.nominatim.baseUrl.description',
    isPublic: true,
  },
  // NAMESPACE: storage
  {
    namespace: 'storage',
    key: 'provider',
    type: 'number',
    defaultValue: null,
    label: 'settings.storage_provider.provider.label',
    description: 'settings.storage_provider.provider.description',
  },
] as const satisfies SettingConfig[]

export const settingNamespaces = [
  ...new Set(DEFAULT_SETTINGS.map((s) => s.namespace)),
] as const
export const settingKeys = [
  ...new Set(DEFAULT_SETTINGS.map((s) => s.key)),
] as const

export type SettingNamespace = (typeof settingNamespaces)[number]
export type SettingKey<N extends SettingNamespace> = Extract<
  (typeof DEFAULT_SETTINGS)[number],
  { namespace: N }
>['key']
