map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen 80;
    server_name _;
    client_max_body_size 1024m;
    resolver 127.0.0.11 valid=10s ipv6=off;
    set $chronoframe_upstream http://chronoframe:3000;
    set $nominatim_upstream http://nominatim:8080;

    proxy_http_version 1.1;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host;

    location /nominatim/ {
        rewrite ^/nominatim/(.*)$ /$1 break;
        proxy_pass $nominatim_upstream;
    }

    location = /maps/style.json {
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
        proxy_pass $chronoframe_upstream/api/maps/style.json$is_args$args;
    }

    location /maps/ {
        proxy_pass http://maplibre:80/;
    }

    location /tiles/ {
        rewrite ^/tiles/(.*)$ /global/$1 break;
        proxy_pass http://pmtiles:8080;
    }

    location / {
        proxy_pass $chronoframe_upstream;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
